### ISSUE TITLE
CutOff_Anmeldungen

### ISSUE THREAD

**Issue by nrammelmueller** [rstropek/htl-schnuppertag#1]
Die Anmeldung zu einem Termin soll nur bis **maximal drei Tage vor dem Termin** möglich sein!
(zB nur bis 21.10 -> für 24.10)

IDEAL: Nur Berücksichtigung von Arbeitstagen (wenn zu komplex -> -3 Tage in Ordnung!!)

So kann sichergestellt werden, dass die Schüler*innen zur Betreuung eingeteilt werden können.

**Comment by rstropek** [comment]
@nrammelmueller Kompromiss: Wochenenden werden ausgenommen, Feiertage werden ignoriert. Ok?

**Comment by nrammelmueller** [comment]
@rstropek  - PERFEKT! :-) Vielen Dank!

**Comment by rstropek** [comment]
@nrammelmueller Rückfrage: Wenn heute der 16. Okt. 2024 ist, soll dann die Anmeldung am 11. Okt. 2024 (drei Arbeitstage vor dem 16.10.) noch möglich sein oder ist der letzte Anmeldetag der 10. Okt.?

**Comment by nrammelmueller** [comment]
@rstropek - Anmeldung am 11.10 soll noch möglich sein - also inklusive! Zwei Tage "Puffer" reichen auf jeden Fall aus, da es hauptsächlich darum geht die Schüler*innen zu informieren ob sie gebraucht werden!
Vielen Dank für die Nachfrage!

**Comment by rstropek** [comment]
Wir haben kein Testsystem, ich muss also "Test in Production" betreiben 😅. Eh ok, oder?

**Comment by rstropek** [comment]
@nrammelmueller Done. Ich habe testweise zwei Termine am 17. und 18.10. eingetragen:
![image](https://github.com/user-attachments/assets/30b180c7-77d3-4134-88c2-508d2d861bf4)

Wie erwartet scheinen diese nicht online auf:
![image](https://github.com/user-attachments/assets/5f0d5784-6a0d-44b9-85c0-3490f2b8e07b)

Bitte um Rückmeldung falls etwas nicht so funktioniert wie gewollt. Bitte issue schließen wenn es passt.

**Comment by nrammelmueller** [comment]
VIELEN DANK für die Umsetzung! :-)
